apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-cm
data:
  DB_NAME: 'mydatabase'
  DB_USERNAME: 'myuser'
  DB_PORT: "5432"
  DB_HOST: '10.100.88.14'
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  DB_PASSWORD: 'bXlwYXNzd29yZA=='
